# Installation de pandas

In [ ]:
%pip install pandas

# Importation de libraries

In [4]:
## import raw data
import pandas as pd
import numpy as np

# Nettoyage de données

In [5]:
raw_data = pd.read_csv("../data/raw/flight_data_2024_sample.csv")

### Aperçu rapide

In [6]:
raw_data.head()

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,4,18,4,2024-04-18,MQ,3535.0,DFW,"Dallas/Fort Worth, TX",Texas,...,0,151.0,144.0,119.0,835.0,0,0,0,0,0
1,2024,1,1,1,2024-01-01,AA,148.0,CLT,"Charlotte, NC",North Carolina,...,0,286.0,273.0,253.0,1773.0,0,0,0,0,0
2,2024,12,12,4,2024-12-12,9E,5440.0,CHA,"Chattanooga, TN",Tennessee,...,0,59.0,50.0,29.0,106.0,0,0,0,0,0
3,2024,4,8,1,2024-04-08,WN,1971.0,OMA,"Omaha, NE",Nebraska,...,0,180.0,177.0,163.0,1099.0,0,0,0,0,0
4,2024,2,16,5,2024-02-16,WN,862.0,BWI,"Baltimore, MD",Maryland,...,0,90.0,96.0,76.0,399.0,0,0,0,0,0

# 1. Compréhension et exploration du dataset
 Avant de commencer le nettoyage des données, nous allons commencer par mieux comprendre les informations qu'elles contiennent.

In [7]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 10000 non-null  int64
 1   month                10000 non-null  int64
 2   day_of_month         10000 non-null  int64
 3   day_of_week          10000 non-null  int64
 4   fl_date              10000 non-null  object
 5   op_unique_carrier    10000 non-null  object
 6   op_carrier_fl_num    10000 non-null  float64
 7   origin               10000 non-null  object
 8   origin_city_name     10000 non-null  object
 9   origin_state_nm      10000 non-null  object
 10  dest                 10000 non-null  object
 11  dest_city_name       10000 non-null  object
 12  dest_state_nm        10000 non-null  object
 13  crs_dep_time         10000 non-null  int64
 14  dep_time             9884 non-null   float64
 15  dep_delay            9884 non-null   float64
 16  taxi_out             9880 non-null   float64
 17  wheels_off           9880 non-null   float64
 18  wheels_on            9873 non-null   float64
 19  taxi_in              9873 non-null   float64
 20  crs_arr_time         10000 non-null  int64
 21  arr_time             9873 non-null   float64
 22  arr_delay            9836 non-null   float64
 23  cancelled            10000 non-null  int64
 24  cancellation_code    122 non-null    object
 25  diverted             10000 non-null  int64
 26  crs_elapsed_time     10000 non-null  float64
 27  actual_elapsed_time  9836 non-null   float64
 28  air_time             9836 non-null   float64
 29  distance             10000 non-null  float64
 30  carrier_delay        10000 non-null  int64
 31  weather_delay        10000 non-null  int64
 32  nas_delay            10000 non-null  int64
 33  security_delay       10000 non-null  int64
 34  late_aircraft_delay  10000 non-null  int64
dtypes: float64(13), int64(13), object(9)
memory usage: 2.7+ MB

In [8]:
raw_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
year,10000.0,NaN,NaN,NaN,2024.0,0.0,2024.0,2024.0,2024.0,2024.0,2024.0
month,10000.0,NaN,NaN,NaN,6.6132,3.377858,1.0,4.0,7.0,10.0,12.0
day_of_month,10000.0,NaN,NaN,NaN,15.843,8.792774,1.0,8.0,16.0,23.0,31.0
day_of_week,10000.0,NaN,NaN,NaN,3.9502,2.00637,1.0,2.0,4.0,6.0,7.0
fl_date,10000,366,2024-08-09,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
op_unique_carrier,10000,15,WN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
op_carrier_fl_num,10000.0,NaN,NaN,NaN,2529.7626,1655.998442,1.0,1172.0,2254.0,3742.0,8771.0
origin,10000,284,ATL,496,NaN,NaN,NaN,NaN,NaN,NaN,NaN
origin_city_name,10000,278,"Chicago, IL",516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
origin_state_nm,10000,52,California,1068,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dest,10000,287,ATL,486,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dest_city_name,10000,281,"Atlanta, GA",486,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dest_state_nm,10000,52,Texas,1132,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crs_dep_time,10000.0,NaN,NaN,NaN,1324.4477,488.544631,22.0,905.0,1320.0,1734.25,2359.0
dep_time,9884.0,NaN,NaN,NaN,1330.160664,504.953299,1.0,910.0,1324.0,1745.0,2400.0
dep_delay,9884.0,NaN,NaN,NaN,13.002428,53.614819,-22.0,-6.0,-2.0,9.25,2011.0
taxi_out,9880.0,NaN,NaN,NaN,17.878644,9.773379,4.0,12.0,15.0,21.0,154.0
wheels_off,9880.0,NaN,NaN,NaN,1353.564879,507.452551,1.0,928.75,1337.0,1759.0,2400.0
wheels_on,9873.0,NaN,NaN,NaN,1460.498936,536.912784,1.0,1046.0,1503.0,1914.0,2400.0
taxi_in,9873.0,NaN,NaN,NaN,8.412944,7.069158,1.0,5.0,6.0,10.0,140.0
crs_arr_time,10000.0,NaN,NaN,NaN,1496.5367,513.230849,2.0,1109.0,1521.0,1925.0,2359.0
arr_time,9873.0,NaN,NaN,NaN,1468.10159,540.10149,1.0,1052.0,1508.0,1921.0,2400.0
arr_delay,9836.0,NaN,NaN,NaN,7.545039,55.803223,-78.0,-15.0,-6.0,10.0,2014.0
cancelled,10000.0,NaN,NaN,NaN,0.0122,0.109783,0.0,0.0,0.0,0.0,1.0
cancellation_code,122,3,B,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diverted,10000.0,NaN,NaN,NaN,0.0042,0.064674,0.0,0.0,0.0,0.0,1.0
crs_elapsed_time,10000.0,NaN,NaN,NaN,147.3725,72.931101,23.0,93.0,130.0,179.0,685.0
actual_elapsed_time,9836.0,NaN,NaN,NaN,141.727837,72.786088,17.0,89.0,125.0,174.0,691.0
air_time,9836.0,NaN,NaN,NaN,115.445506,70.736184,8.0,64.0,98.0,145.0,635.0
distance,10000.0,NaN,NaN,NaN,838.3466,598.526507,31.0,404.0,680.0,1072.0,5095.0
carrier_delay,10000.0,NaN,NaN,NaN,4.8709,33.502392,0.0,0.0,0.0,0.0,2011.0
weather_delay,10000.0,NaN,NaN,NaN,1.0831,15.821031,0.0,0.0,0.0,0.0,664.0
nas_delay,10000.0,NaN,NaN,NaN,3.0271,15.755545,0.0,0.0,0.0,0.0,454.0
security_delay,10000.0,NaN,NaN,NaN,0.0088,0.381231,0.0,0.0,0.0,0.0,22.0
late_aircraft_delay,10000.0,NaN,NaN,NaN,6.1422,29.632624,0.0,0.0,0.0,0.0,995.0

In [9]:
raw_data.shape

(10000, 35)

In [10]:
raw_data.columns

Index(['year', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name',
       'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm',
       'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off',
       'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay',
       'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [22]:
# 1️⃣ Convert date column
raw_data['fl_date'] = pd.to_datetime(raw_data['fl_date'], errors='coerce')
# 2️⃣ Ensure numeric columns are numeric (even if they contain NaN or wrong chars)
numeric_cols = [
    'year', 'month', 'day_of_month', 'day_of_week',
    'op_carrier_fl_num', 'crs_dep_time', 'dep_time', 'dep_delay',
    'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in', 'crs_arr_time',
    'arr_time', 'arr_delay', 'cancelled', 'diverted', 'crs_elapsed_time',
    'actual_elapsed_time', 'air_time', 'distance',
    'carrier_delay', 'weather_delay', 'nas_delay',
    'security_delay', 'late_aircraft_delay'
]
raw_data[numeric_cols] = raw_data[numeric_cols].apply(pd.to_numeric, errors='coerce')
# 3️⃣ Convert categorical columns to 'category' type
cat_cols = [
    'op_unique_carrier', 'origin', 'origin_city_name', 'origin_state_nm',
    'dest', 'dest_city_name', 'dest_state_nm', 'cancellation_code'
]
for col in cat_cols:
    raw_data[col] = raw_data[col].astype('category')


# verify the conversion
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 10000 non-null  int64
 1   month                10000 non-null  int64
 2   day_of_month         10000 non-null  int64
 3   day_of_week          10000 non-null  int64
 4   fl_date              10000 non-null  datetime64[ns]
 5   op_unique_carrier    10000 non-null  category
 6   op_carrier_fl_num    10000 non-null  float64
 7   origin               10000 non-null  category
 8   origin_city_name     10000 non-null  category
 9   origin_state_nm      10000 non-null  category
 10  dest                 10000 non-null  category
 11  dest_city_name       10000 non-null  category
 12  dest_state_nm        10000 non-null  category
 13  crs_dep_time         0 non-null      float64
 14  dep_time             9884 non-null   float64
 15  dep_delay            9884 non-null   float64
 16  taxi_out             9880 non-null   float64
 17  wheels_off           9880 non-null   float64
 18  wheels_on            9873 non-null   float64
 19  taxi_in              9873 non-null   float64
 20  crs_arr_time         10000 non-null  int64
 21  arr_time             9873 non-null   float64
 22  arr_delay            9836 non-null   float64
 23  cancelled            10000 non-null  int64
 24  cancellation_code    122 non-null    category
 25  diverted             10000 non-null  int64
 26  crs_elapsed_time     10000 non-null  float64
 27  actual_elapsed_time  9836 non-null   float64
 28  air_time             9836 non-null   float64
 29  distance             10000 non-null  float64
 30  carrier_delay        10000 non-null  int64
 31  weather_delay        10000 non-null  int64
 32  nas_delay            10000 non-null  int64
 33  security_delay       10000 non-null  int64
 34  late_aircraft_delay  10000 non-null  int64
 35  crs_dep_time_hhmm    10000 non-null  object
 36  dep_time_hhmm        9884 non-null   object
 37  crs_arr_time_hhmm    10000 non-null  object
 38  arr_time_hhmm        9873 non-null   object
 39  wheels_off_hhmm      9880 non-null   object
 40  wheels_on_hhmm       9873 non-null   object
dtypes: category(8), datetime64[ns](1), float64(14), int64(12), object(6)
memory usage: 2.7+ MB

In [23]:
time_cols = ['crs_dep_time', 'dep_time', 'wheels_off', 'wheels_on', 'crs_arr_time',
    'arr_time']
# Avant la modification du format 
raw_data[['crs_dep_time', 'dep_time', 'wheels_off', 'wheels_on', 'crs_arr_time',
    'arr_time']].head()

   crs_dep_time  dep_time  wheels_off  wheels_on  crs_arr_time  arr_time
0           NaN    1015.0      1036.0     1135.0          1149    1139.0
1           NaN    1633.0      1647.0     1900.0          1923    1906.0
2           NaN     952.0      1005.0     1034.0          1059    1042.0
3           NaN    1334.0      1342.0     1425.0          1430    1431.0
4           NaN    1333.0      1349.0     1505.0          1510    1509.0

In [24]:

# Fonction pour convertir HHMM → hh:mm
def hhmm_format(hhmm):
    try:
        hhmm = int(hhmm)          # s'assure que c'est un entier
        hours = hhmm // 100
        mins = hhmm % 100
        return f"{hours:02d}:{mins:02d}"
    except:
        return None  # gère les valeurs manquantes ou incorrectes

# Appliquer la conversion à toutes les colonnes de temps
for col in time_cols:
    raw_data[col + '_hhmm'] = raw_data[col].apply(hhmm_format)

# Vérifier le résultat
raw_data[['crs_dep_time_hhmm', 'dep_time_hhmm', 'wheels_off_hhmm', 'wheels_on_hhmm', 'crs_arr_time_hhmm',
    'arr_time_hhmm']].head()

,crs_dep_time_hhmm,dep_time_hhmm,wheels_off_hhmm,wheels_on_hhmm,crs_arr_time_hhmm,arr_time_hhmm
0,None,10:15,10:36,11:35,11:49,11:39
1,None,16:33,16:47,19:00,19:23,19:06
2,None,09:52,10:05,10:34,10:59,10:42
3,None,13:34,13:42,14:25,14:30,14:31
4,None,13:33,13:49,15:05,15:10,15:09

In [25]:
raw_data['crs_dep_time'] = raw_data['crs_dep_time_hhmm']
raw_data.head()

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,weather_delay,nas_delay,security_delay,late_aircraft_delay,crs_dep_time_hhmm,dep_time_hhmm,crs_arr_time_hhmm,arr_time_hhmm,wheels_off_hhmm,wheels_on_hhmm
0,2024,4,18,4,2024-04-18,MQ,3535.0,DFW,"Dallas/Fort Worth, TX",Texas,...,0,0,0,0,None,10:15,11:49,11:39,10:36,11:35
1,2024,1,1,1,2024-01-01,AA,148.0,CLT,"Charlotte, NC",North Carolina,...,0,0,0,0,None,16:33,19:23,19:06,16:47,19:00
2,2024,12,12,4,2024-12-12,9E,5440.0,CHA,"Chattanooga, TN",Tennessee,...,0,0,0,0,None,09:52,10:59,10:42,10:05,10:34
3,2024,4,8,1,2024-04-08,WN,1971.0,OMA,"Omaha, NE",Nebraska,...,0,0,0,0,None,13:34,14:30,14:31,13:42,14:25
4,2024,2,16,5,2024-02-16,WN,862.0,BWI,"Baltimore, MD",Maryland,...,0,0,0,0,None,13:33,15:10,15:09,13:49,15:05

## 2. Traitement des valeurs manquantes
### A partir de là, nous allons commencer le nettoyage de ces données, en commencant par détécter et traiter les valeurs manquantes

In [9]:
raw_data.isnull().sum()

year                      0
month                     0
day_of_month              0
day_of_week               0
fl_date                   0
op_unique_carrier         0
op_carrier_fl_num         0
origin                    0
origin_city_name          0
origin_state_nm           0
dest                      0
dest_city_name            0
dest_state_nm             0
crs_dep_time              0
dep_time                116
dep_delay               116
taxi_out                120
wheels_off              120
wheels_on               127
taxi_in                 127
crs_arr_time              0
arr_time                127
arr_delay               164
cancelled                 0
cancellation_code      9878
diverted                  0
crs_elapsed_time          0
actual_elapsed_time     164
air_time                164
distance                  0
carrier_delay             0
weather_delay             0
nas_delay                 0
security_delay            0
late_aircraft_delay       0
dtype: int64